use_frameworks!

platform :ios, '8.0'

target 'MBBase_CTMediator_Example' do
  pod 'MBBase_CTMediator', :path => '../'

  target 'MBBase_CTMediator_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
